import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/src/styles/Home.module.css'
import { FruitBlock } from '../components/FruitBlock'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Fruit List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div class="content-center" className={styles.description}>
          <h1 class="text-6xl font-bold underline">Fruit List</h1>
        </div>
        <FruitBlock />
      </main>
    </>
  )
}
